export const GET_ME_SUCCESS = "GET_ME_SUCCESS"
export const GET_ME_LOADING = "GET_ME_LOADING"
export const GET_ME_FAILED = "GET_ME_FAILED"

export const GET_JOBS_SUCCES = "GET_JOBS_SUCCES"
export const GET_JOBS_LOADING = "GET_JOBS_LOADING"
export const GET_JOBS_FAILED = "GET_JOBS_FAILED"

export const GET_RESUME_SUCCES = "GET_RESUME_SUCCES"
export const GET_RESUME_LOADING = "GET_RESUME_LOADING"
export const GET_RESUME_FAILED = "GET_RESUME_FAILED"

export const GET_CATEGORY_SUCCES = "GET_CATEGORY_SUCCES"
export const GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING"
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED"

export const GET_JOBS_DETAIL_SUCCES = "GET_JOBS_DETAIL_SUCCES"
export const GET_JOBS_DETAIL_LOADING = "GET_JOBS_DETAIL_LOADING"
export const GET_JOBS_DETAIL_FAILED = "GET_JOBS_DETAIL_FAILED"

export const POST_RESUME_SUCCES = "POST_RESUME_SUCCES"
export const POST_RESUME_LOADING = "POST_RESUME_LOADING"
export const POST_RESUME_FAILED = "POST_RESUME_FAILED"

export const POST_EXPERIENCE_ONE_SUCCES = "POST_EXPERIENCE_ONE_SUCCES"
export const POST_EXPERIENCE_ONE_LOADING = "POST_EXPERIENCE_ONE_LOADING"
export const POST_EXPERIENCE_ONE_FAILED = "POST_EXPERIENCE_ONE_FAILED"

export const POST_EXPERIENCE_TWO_SUCCES = "POST_EXPERIENCE_TWO_SUCCES"
export const POST_EXPERIENCE_TWO_LOADING = "POST_EXPERIENCE_TWO_LOADING"
export const POST_EXPERIENCE_TWO_FAILED = "POST_EXPERIENCE_TWO_FAILED"

export const POST_EXPERIENCE_THREE_SUCCES = "POST_EXPERIENCE_THREE_SUCCES"
export const POST_EXPERIENCE_THREE_LOADING = "POST_EXPERIENCE_THREE_LOADING"
export const POST_EXPERIENCE_THREE_FAILED = "POST_EXPERIENCE_THREE_FAILED"

export const AUTH_USER = "AUTH_USER"
export const LOGOUT = "LOGOUT"

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_LOADING = 'SIGNUP_LOADING'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'

export const GET_CRUD_SUCCESS = 'GET_CRUD_SUCCESS'
export const GET_CRUD_LOADING = 'GET_CRUD_LOADING'
export const GET_CRUD_FAILED = 'GET_CRUD_FAILED'

export const CREATE_CRUD_SUCCESS = 'CREATE_CRUD_SUCCESS'
export const CREATE_CRUD_LOADING = 'CREATE_CRUD_LOADING'
export const CREATE_CRUD_FAILED = 'CREATE_CRUD_FAILED'

export const EDIT_CRUD_SUCCESS = 'EDIT_CRUD_SUCCESS'
export const EDIT_CRUD_LOADING = 'EDIT_CRUD_LOADING'
export const EDIT_CRUD_FAILED = 'EDIT_CRUD_FAILED'

export const DELETE_CRUD_SUCCESS = 'DELETE_CRUD_SUCCESS'
export const DELETE_CRUD_LOADING = 'DELETE_CRUD_LOADING'
export const DELETE_CRUD_FAILED = 'DELETE_CRUD_FAILED'
